# Generated by Django 3.1 on 2021-01-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=500)),
                ('studentid', models.CharField(max_length=100)),
                ('pin1', models.IntegerField()),
                ('pin2', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
