# Generated by Django 3.1 on 2021-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0002_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='details',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
