# Generated by Django 3.1 on 2021-01-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0005_auto_20210108_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
