# Generated by Django 3.1 on 2021-01-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0006_details_pin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
        migrations.AddField(
            model_name='details',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
