# Generated by Django 3.1 on 2021-01-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0007_auto_20210108_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
