# Generated by Django 3.1 on 2021-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0010_auto_20210110_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
