# Generated by Django 3.1 on 2021-01-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0011_auto_20210111_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
