# Generated by Django 3.1 on 2021-01-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0012_auto_20210111_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
