# Generated by Django 3.1 on 2021-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_fees_app', '0014_studentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='Slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
