# Generated by Django 3.1 on 2021-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210319_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
